[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py

addopts =
    -v
    --tb=short
    --strict-markers
    --cov=config
    --cov=controllers
    --cov=database
    --cov=gui
    --cov=models
    --cov=monitor
    --cov=services
    --cov=utils
    --cov-report=term-missing
    --cov-report=html

norecursedirs =
    tests
    .venv
    __pycache__