name: Latest Development Build

on:
  push:
    branches:
      - main
    paths:
      - "assets/**"
      - "controllers/**"
      - "database/**"
      - "gui/**"
      - "icons/**"
      - "models/**"
      - "monitor/**"
      - "resources/**"
      - "services/**"
      - "themes/**"
      - "utils/**"
      - "config.py"
      - "main.py"
      - "main.spec"
      - "requirements.txt"
      - "settings.json"
      - "version_info.txt"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download GeoLite Database
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path resources\geoip
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-Country.mmdb" `
            -OutFile "resources\geoip\GeoLite2-Country.mmdb"

      - name: Build application
        shell: powershell
        run: |
          pyinstaller main.spec --clean --noconfirm

      - name: Create ZIP
        shell: powershell
        run: |
          Compress-Archive `
            -Path dist\main\* `
            -DestinationPath NetWatch-latest.zip `
            -Force

      - name: Publish Latest Development Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: NetWatch Latest Development Build
          artifacts: NetWatch-latest.zip

          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: true

          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          omitBodyDuringUpdate: true

          makeLatest: false
          token: ${{ secrets.GITHUB_TOKEN }}